services:
  - type: web
    name: fasal-saathi
    env: docker
    plan: starter
    region: oregon
    dockerfilePath: ./Dockerfile
    buildCommand: ""
    startCommand: ""
    envVars:
      - key: PORT
        value: 8000
      - key: HOST
        value: 0.0.0.0
      - key: GEMINI_API_KEY
        sync: false
      - key: GOOGLE_CLOUD_PROJECT
        sync: false
      - key: REPORT_SIGNING_SECRET_NAME
        value: report-signing-key
      - key: TWILIO_ACCOUNT_SID
        sync: false
      - key: TWILIO_AUTH_TOKEN
        sync: false
      - key: TWILIO_WHATSAPP_NUMBER
        sync: false
      - key: REDIS_URL
        fromService:
          name: agri-redis
          type: keyvalue

  - type: web
    name: agri-celery-worker
    env: docker
    plan: starter
    region: oregon
    dockerfilePath: ./Dockerfile
    dockerContext: .
    buildCommand: ""
    startCommand: "celery -A celery_worker.celery_app worker --loglevel=info --pool=solo"
    envVars:
      - key: REDIS_URL
        fromService:
          name: agri-redis
          type: keyvalue
      - key: GEMINI_API_KEY
        sync: false

  - type: keyvalue
    name: agri-redis
    plan: starter
    region: oregon